name: TestX CI/CD

on:
  workflow_dispatch

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19.0.2
        
    - name: listing the files of checkout
      run: ls -ltR

    - name: Running the maven test
      run: mvn clean install

    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-report
        path: target/cucumber-html-reports
