# checking for the Github actions for the test case 1
name: Test-case2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'test'

jobs:
  trigger-another-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow on another branch
        run: gh workflow run main.yml-R SaiPrabhu88
github-action-maven-example-start -b test-case1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

