name: TestX CI/CD

on:
  workflow_dispatch

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19.0.2
        
    - name: listing the files of checkout
      run: ls -ltR

    - name: Running the maven test
      run: |
        mvn -B package --file pom.xml
        ls -ltR
        # mkdir staging && cp target/*jar-with-dependencies.jar staging
