name: Main Workflow-2
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          ref: "test-case1"
      - name: Listing the files and Directories
        run: |
          ls -ltR