name: Main Workflow-1
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Main Workflow-1
        run: echo "Running main.yml workflow"

      - name: Execute the Test command
        run: echo "Hello Main1.yml file"