# checking for the Github actions for the test case 1
name: Test-case2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'test'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19.0.2
        
    - name: listing the files of checkout
      run: ls -ltR

    - name: Running the maven test
      run: |
        mvn -B package --file pom.xml
    
    - name: Listing the files and Directories
      run: |
        ls -ltR

    - name: creating the staging directory and copying the build file
      run: mkdir staging && cp target/*jar-with-dependencies.jar staging

    - name: Upload the artifacts
      uses: actions/upload-artifact@v4
      with:
        name: upload-artifacts
        path: staging
